-- DELETE FROM Course
-- DBCC CHECKIDENT ('Course', RESEED, 0);

INSERT INTO Course (Course_Name, Duration_Hrs) VALUES
('Intro to Linux', 9),
('Web Dev with PHP & MySQL', 12),
('JS & Frontend Frameworks', 15),
('Python for Web Dev', 18),
('Backend Dev with Node.js', 21),
('API Dev & Integration', 24),
('Software Eng Principles', 27),
('DB Design & Optimization', 30),
('Git & GitHub Version Ctrl', 6),
('CI/CD Pipelines', 9),
('C# Programming Basics', 12),
('ASP.NET Core Dev', 15),
('Entity Framework & DB Mgmt', 18),
('Frontend with Angular & Vue', 21),
('Web API Dev with .NET', 24),
('Microservices in .NET', 27),
('Cloud Deploy with Azure', 30),
('Secure Coding in .NET', 6),
('Software Testing & Debugging', 9),
('Agile & Scrum for Devs', 12),
('Python for Data Science', 15),
('Stats & Prob for Data Analysis', 18),
('Machine Learning Basics', 21),
('Deep Learning with TensorFlow', 24),
('Natural Language Processing', 27),
('Computer Vision & Imaging', 30),
('Data Viz with Power BI & Tableau', 6),
('Time Series Forecasting', 9),
('Big Data with Spark', 12),
('AI Model Deployment', 15),
('SQL for Data Analysis', 18),
('Data Warehousing Basics', 21),
('Power BI for Business Intel', 24),
('Tableau for Data Visualization', 27),
('Data Cleaning & Preprocessing', 30),
('Business Analytics with Excel', 6),
('Predictive Analytics', 9),
('Google Analytics & Marketing', 12),
('Financial Data Analysis', 15),
('Dashboard Development', 18),
('Intro to Cloud Computing', 21),
('AWS Fundamentals', 24),
('Microsoft Azure Basics', 27),
('Google Cloud Platform (GCP)', 30),
('Kubernetes & Containers', 6),
('DevOps: Jenkins, Ansible, Terraform', 9),
('Cloud Security Best Practices', 12),
('Serverless Computing', 15),
('Cloud Cost Optimization', 18),
('CI/CD Automation', 21),
('Network Security Basics', 24),
('Ethical Hacking Techniques', 27),
('Penetration Testing', 30),
('Web App Security', 6),
('Malware Analysis', 9),
('Cyber Threat Intelligence', 12),
('Security Ops & Incident Response', 15),
('Cryptography & Secure Comm', 18),
('Cloud Security & Compliance', 21),
('Digital Forensics', 24),
('Embedded C Programming', 27),
('Microcontroller Programming', 30),
('Real-Time Operating Systems', 6),
('IoT Communication Protocols', 9),
('Edge Computing & IoT Analytics', 12),
('Embedded Linux Development', 15),
('IoT Security & Privacy', 18),
('Sensor & Actuator Integration', 21),
('Wireless Communication in IoT', 24),
('PCB Design & Prototyping', 27),
('Java & Kotlin for Android', 30),
('Swift & Obj-C for iOS', 6),
('Cross-Platform Dev with Flutter', 9),
('UI/UX Design for Mobile Apps', 12),
('Mobile App Backend Dev', 15),
('Firebase for Mobile Apps', 18),
('Mobile App Security', 21),
('Performance Optimization', 24),
('AR & VR in Mobile Apps', 27),
('App Deployment & Monetization', 30),
('HTML, CSS & JavaScript', 6),
('Responsive Web Design', 9),
('Frontend with React & Angular', 12),
('UI/UX Design Principles', 15),
('API Integration & AJAX', 18),
('Web Performance Optimization', 21),
('SEO & Web Accessibility', 24),
('Web Security Best Practices', 27),
('Progressive Web Apps (PWA)', 30),
('Web Deployment & Hosting', 6),
('Intro to Game Development', 9),
('Unity Game Engine Basics', 12),
('Unreal Engine Development', 15),
('AR/VR Development with Unity', 18),
('Game Physics & Mechanics', 21),
('3D Modeling & Animation', 24),
('Multiplayer Game Development', 27),
('AI in Games', 30),
('Game Monetization Strategies', 6),
('Game Performance Optimization', 9),
('SEO & Digital Marketing', 12),
('Google Ads & PPC Campaigns', 15),
('Email Marketing Strategies', 18),
('Content Marketing & Copywriting', 21),
('Affiliate Marketing & E-commerce', 24),
('Data Analytics in Marketing', 27),
('Branding & Online Reputation', 30),
('Mobile Marketing & Promotion', 6),
('Influencer Marketing', 9),
('Networking Basics & Protocols', 12),
('CCNA Routing & Switching', 15),
('Wireless Networking & Security', 18),
('Network Virtualization & SDN', 21),
('Network Monitoring', 24),
('Firewall & VPN Configuration', 27),
('VoIP & Telecommunication', 30),
('Cloud Networking & Edge', 6),
('Incident Response & Threat Mgmt', 9),
('IPv6 & Networking Trends', 12),
('IT Support & Troubleshooting', 15),
('Windows & Linux Admin', 18),
('Virtualization & Hyper-V', 21),
('Storage & Backup Solutions', 24),
('Network Infra Management', 27),
('Cloud Infra Services', 30),
('IT Security & Compliance', 6),
('Load Balancing & Traffic Mgmt', 9),
('Disaster Recovery Planning', 12),
('IT Service Management (ITSM)', 15),
('Blockchain Fundamentals', 18),
('Smart Contracts with Solidity', 21),
('Ethereum & Hyperledger', 24),
('Cryptocurrency & Tokenization', 27),
('DApps & Blockchain Security', 30),
('Web3 & Metaverse Development', 6),
('Blockchain in Finance & Supply', 9),
('Consensus Mechanisms', 12),
('NFT & Smart Contract Marketplaces', 15),
('SQL & Relational Databases', 18),
('NoSQL Databases (MongoDB)', 21),
('DB Design & Normalization', 24),
('Query Optimization & Indexing', 27),
('Database Security & Access Ctrl', 30),
('Data Replication & Backup', 6),
('Big Data Storage & Processing', 9),
('Cloud Databases (AWS RDS)', 12),
('ETL & Data Integration', 15),
('Database Performance Tuning', 18),
('Manual Testing Fundamentals', 21),
('Test Automation with Selenium', 24),
('API Testing with Postman', 27),
('Performance Testing with JMeter', 30),
('Security Testing Basics', 6),
('Mobile App Testing Strategies', 9),
('CI/CD Integration in Testing', 12),
('Agile & DevOps Testing', 15),
('Regression & Load Testing', 18),
('Test Management & Documentation', 21);
