-- DELETE FROM Company
-- DBCC CHECKIDENT ('Company', RESEED, 0);
INSERT INTO Company (Name, Location, Type) VALUES
('Maridive & Oil Servi', 'Egypt', 'National'),
('El Araby Group', 'Egypt', 'National'),
('Etisalat Misr', 'Egypt', 'National'),
('Emaar Misr', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('Ezz Steel', 'Egypt', 'National'),
('Edita Food Industrie', 'Egypt', 'National'),
('B-Tech', 'Egypt', 'National'),
('Orascom Construction', 'Egypt', 'National'),
('Ezz Steel', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('El Araby Group', 'Egypt', 'National'),
('B-Tech', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('Telecom Egypt', 'Egypt', 'National'),
('SODIC', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('B-Tech', 'Egypt', 'National'),
('El Araby Group', 'Egypt', 'National'),
('Orange Egypt', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('Maridive & Oil Servi', 'Egypt', 'National'),
('Telecom Egypt', 'Egypt', 'National'),
('GB Auto', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('El Araby Group', 'Egypt', 'National'),
('El Araby Group', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('Edita Food Industrie', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('Maridive & Oil Servi', 'Egypt', 'National'),
('CIB Egypt', 'Egypt', 'National'),
('Edita Food Industrie', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('Emaar Misr', 'Egypt', 'National'),
('Orascom Construction', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('Ezz Steel', 'Egypt', 'National'),
('Emaar Misr', 'Egypt', 'National'),
('Fawry', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('CIB Egypt', 'Egypt', 'National'),
('Orange Egypt', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('Fawry', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('Telecom Egypt', 'Egypt', 'National'),
('Ezz Steel', 'Egypt', 'National'),
('Orange Egypt', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('SODIC', 'Egypt', 'National'),
('Edita Food Industrie', 'Egypt', 'National'),
('Orascom Construction', 'Egypt', 'National'),
('Etisalat Misr', 'Egypt', 'National'),
('B-Tech', 'Egypt', 'National'),
('Ezz Steel', 'Egypt', 'National'),
('Edita Food Industrie', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('El Araby Group', 'Egypt', 'National'),
('Fawry', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('SODIC', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('Maridive & Oil Servi', 'Egypt', 'National'),
('Edita Food Industrie', 'Egypt', 'National'),
('Orange Egypt', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('Fawry', 'Egypt', 'National'),
('Vodafone Egypt', 'Egypt', 'National'),
('Vodafone Egypt', 'Egypt', 'National'),
('GB Auto', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('Fawry', 'Egypt', 'National'),
('Orange Egypt', 'Egypt', 'National'),
('Telecom Egypt', 'Egypt', 'National'),
('Telecom Egypt', 'Egypt', 'National'),
('Telecom Egypt', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('Maridive & Oil Servi', 'Egypt', 'National'),
('Telecom Egypt', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('El Araby Group', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('El Araby Group', 'Egypt', 'National'),
('Telecom Egypt', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('CIB Egypt', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('Edita Food Industrie', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('SODIC', 'Egypt', 'National'),
('Etisalat Misr', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('Edita Food Industrie', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('Emaar Misr', 'Egypt', 'National'),
('Vodafone Egypt', 'Egypt', 'National'),
('El Sewedy Electric', 'Egypt', 'National'),
('GB Auto', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('B-Tech', 'Egypt', 'National'),
('Ezz Steel', 'Egypt', 'National'),
('SODIC', 'Egypt', 'National'),
('Orascom Construction', 'Egypt', 'National'),
('Maridive & Oil Servi', 'Egypt', 'National'),
('Emaar Misr', 'Egypt', 'National'),
('Orange Egypt', 'Egypt', 'National'),
('Orange Egypt', 'Egypt', 'National'),
('Edita Food Industrie', 'Egypt', 'National'),
('GB Auto', 'Egypt', 'National'),
('Arab Contractors', 'Egypt', 'National'),
('El Araby Group', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('Maridive & Oil Servi', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('Fawry', 'Egypt', 'National'),
('Banque Misr', 'Egypt', 'National'),
('Ezz Steel', 'Egypt', 'National'),
('Fawry', 'Egypt', 'National'),
('Fawry', 'Egypt', 'National'),
('SODIC', 'Egypt', 'National'),
('Orange Egypt', 'Egypt', 'National'),
('Fawry', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('Palm Hills Developme', 'Egypt', 'National'),
('Juhayna', 'Egypt', 'National'),
('CIB Egypt', 'Egypt', 'National'),
('GB Auto', 'Egypt', 'National'),
('GB Auto', 'Egypt', 'National'),
('Siemens', 'Germany', 'Multi-National'),
('Boeing', 'USA', 'Multi-National'),
('Tesla', 'USA', 'Multi-National'),
('Intel', 'USA', 'Multi-National'),
('Microsoft', 'USA', 'Multi-National'),
('Siemens', 'Germany', 'Multi-National'),
('Unilever', 'UK', 'Multi-National'),
('BMW', 'Germany', 'Multi-National'),
('Toyota', 'Japan', 'Multi-National'),
('BMW', 'Germany', 'Multi-National'),
('Unilever', 'UK', 'Multi-National'),
('BMW', 'Germany', 'Multi-National'),
('Toyota', 'Japan', 'Multi-National'),
('Apple', 'USA', 'Multi-National'),
('Philips', 'Netherlands', 'Multi-National'),
('Nestlé', 'Switzerland', 'Multi-National'),
('Siemens', 'Germany', 'Multi-National'),
('Intel', 'USA', 'Multi-National'),
('Volkswagen', 'Germany', 'Multi-National'),
('Volkswagen', 'Germany', 'Multi-National'),
('IBM', 'USA', 'Multi-National'),
('Unilever', 'UK', 'Multi-National'),
('Airbus', 'France', 'Multi-National'),
('BMW', 'Germany', 'Multi-National'),
('Samsung', 'South Korea', 'Multi-National'),
('Sony', 'Japan', 'Multi-National'),
('Tencent', 'China', 'Multi-National'),
('Volkswagen', 'Germany', 'Multi-National'),
('Boeing', 'USA', 'Multi-National'),
('Huawei', 'China', 'Multi-National'),
('Toyota', 'Japan', 'Multi-National'),
('Toyota', 'Japan', 'Multi-National'),
('BMW', 'Germany', 'Multi-National'),
('Tesla', 'USA', 'Multi-National'),
('IBM', 'USA', 'Multi-National'),
('Toyota', 'Japan', 'Multi-National'),
('Apple', 'USA', 'Multi-National'),
('Unilever', 'UK', 'Multi-National'),
('Apple', 'USA', 'Multi-National'),
('LOréal', 'France', 'Multi-National'),
('Nestlé', 'Switzerland', 'Multi-National'),
('BMW', 'Germany', 'Multi-National'),
('Boeing', 'USA', 'Multi-National'),
('Nestlé', 'Switzerland', 'Multi-National'),
('Boeing', 'USA', 'Multi-National'),
('Toyota', 'Japan', 'Multi-National'),
('IBM', 'USA', 'Multi-National'),
('Sony', 'Japan', 'Multi-National'),
('Apple', 'USA', 'Multi-National'),
('Unilever', 'UK', 'Multi-National');